name: Publish One Click Apps

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - run: touch dist/.nojekyll
      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: ./dist
          clean: true
          single-commit: true
          git-config-name: 'github-actions'
          git-config-email: '<>'
